# This is free software released into the public domain (CC0 license).


require 'time'
require 'tmpdir'

require 'createdeb/debdesc'

module Createdeb; end

class Createdeb::Engine
	def initialize(options, log)
		@options = options
		@log = log

		@now = Time.now

		@pkg = @options[:input_file].split('/').last.sub('.debdesc', '')
		@orig_dir ||= @options[:input_file].sub('.debdesc', '')
	end

	def setup!
		@debdesc = Createdeb::Debdesc.new(@options[:input_file], @log)

		@tmp_dir = Dir.mktmpdir('createdeb-')
		@work_dir = @tmp_dir + "/" + pkg_name + '-' + version
		FileUtils.mkdir_p(@work_dir)
	end

	def tear_down!
		FileUtils.remove_entry_secure(@tmp_dir) unless @options[:debug]
	end

	def copy_files!
		FileUtils.mkdir_p("#{@work_dir}/files")

		@to_copy = @debdesc.fields('Copy')
		@to_copy.each do |field|
			file, dest = field.pair_value

			orig_dir = "#{@orig_dir}/files"
			if !File.directory?(orig_dir)
				orig_dir = @orig_dir
			end

			# TODO: test that different files with the same name do not get overwritten
			rel_dir = File.dirname(file)
			dest_dir = "#{@work_dir}/files/#{rel_dir}/"

			FileUtils.mkdir_p(dest_dir)
			FileUtils.cp("#{orig_dir}/#{file}", dest_dir)
		end
	end

	def create_patches!
		@to_diff = @debdesc.fields('Diff')
		@to_diff.each do |field|
			file = field.simple_value
			diff_cmd = ["diff", "-u2", "#{@orig_dir}/diff/#{file}.orig", "#{@orig_dir}/diff/#{file}"]
			patch_path = "#{@work_dir}/patches/#{file}.diff"
			patch = ""
			IO.popen(diff_cmd.join(' ')) { |io| patch = io.read }

			prefix = @options[:input_file].sub('.debdesc', '') + '/diff/'
			patch.sub!(prefix, '').sub!(prefix, '')

			FileUtils.mkdir_p(File.dirname(patch_path))
			File.open(patch_path, "w") { |file| file << patch }
		end
	end

	def create_fixed_debian_files!
		deb_dir = @work_dir + '/debian'
		FileUtils.mkdir(deb_dir)

		FileUtils.mkdir(deb_dir + '/source')
		File.open(deb_dir + '/source' + '/format', 'w') { |f| f << "3.0 (native)\n" }

		File.open(deb_dir + '/compat', 'w') { |f| f << "9\n" }

		File.open(deb_dir + '/rules', 'w') do |f|
			f << "#!/usr/bin/make -f\n"
			f << "\n"
			f << "%:\n"
			f << "\tdh $@\n"

		end
		FileUtils.chmod(0o755, deb_dir + '/rules')
	end

	def create_maintscripts!
		user_postinst_script = @debdesc.fields('File').find { |f| f.lines.first.strip == 'postinst' }
		user_prerm_script    = @debdesc.fields('File').find { |f| f.lines.first.strip == 'prerm' }
		user_postrm_script   = @debdesc.fields('File').find { |f| f.lines.first.strip == 'postrm' }

		postinst_script = user_postinst_script.multiline_value[1] unless user_postinst_script.nil?
		prerm_script    = user_prerm_script.multiline_value[1] unless user_prerm_script.nil?
		postrm_script   = user_postrm_script.multiline_value[1] unless user_postrm_script.nil?

		if !@to_diff.empty?
			if !postinst_script.nil? && !prerm_script.nil?
				raise "Cannot mix postinst/prerm scripts and Diff directives"
			end

			postinst_script = "#!/bin/sh\n" + @to_diff.map { |d| "patch -p0 -i /usr/share/#{pkg_name}/patches/#{d.simple_value}.diff\n" }.join('')
			prerm_script    = "#!/bin/sh\n" + @to_diff.map { |d| "patch -R -p0 -i /usr/share/#{pkg_name}/patches/#{d.simple_value}.diff\n" }.join('')

			@debdesc.add_to_field_folded('Pre-Depends', 'patch', ',')
		end

		scripts = {
			'postinst' => postinst_script,
			'prerm' => prerm_script,
			'postrm' => postrm_script,
		}

		maintscripts_dir = "#{@work_dir}/debian"

		scripts.each do |script, content|
			if content.nil?
				next
			end

			FileUtils.mkdir_p(maintscripts_dir)

			File.open("#{maintscripts_dir}/#{script}", "w") { |f| f << content }
		end
	end

	def create_install_file!
		File.open("#{@work_dir}/debian/install", "w") do |f|
			f << @to_copy.map { |c| val = c.pair_value; "files/#{val.first} #{val.last}\n" }
			f << @to_diff.map { |d| patch = "#{d.simple_value}.diff" ; "patches/#{patch} /usr/share/#{pkg_name}/patches/#{File.dirname(patch)}\n" }
		end
	end

	def create_changelog!
		# TODO: create proper changelog
		File.open("#{@work_dir}/debian/changelog", "w") do |f|

			f << "#{@pkg} (#{version}) unstable; urgency=low\n"
			f << "\n"
			f << "  * Generated by createdeb\n"
			f << "\n"
			f << " -- #{maintainer}  #{@now.rfc2822}\n"
		end
	end

	def create_control!
		File.open("#{@work_dir}/debian/control", "w") do |f|
			f << "Source: #{@pkg}\n"
			f << "Section: misc\n"
			f << "Priority: optional\n"
			f << "Build-Depends: debhelper (>=9)\n"
			f << "Maintainer: #{maintainer}\n"
			f << "Standards-Version: 3.9.2\n"

			f << "\n"

			f << "Package: #{pkg_name}\n"
			f << "Architecture: #{target_arch}\n"
			f << "Description: #{description}\n"

			%w{Pre-Depends Depends Recommends Suggests Enhances}.each do |field|
				f << "#{field}: #{@debdesc.field(field).folded_value}\n" unless !@debdesc.has_field(field)
			end
		end
	end

	def build_package!
		opts = []

		opts << '-b' if !@options[:full]
		opts << '-F' if @options[:full]

		if !@options[:sign]
			opts << '-us'
			opts << '-uc'
		end

		Dir.chdir(@work_dir) do
			build_cmd = ['dpkg-buildpackage', '-rfakeroot'] + opts
			IO.popen(build_cmd.join(' ')) do |io|
				output = io.read
				# TODO: write in log
				@log.debug output
			end
		end

		if !$?.success?
			raise "Error during build, see log"
		end
	end

	def move_package!
		base_name = pkg_name + '_' + version

		deb_name = "#{base_name}_#{target_arch}.deb"
		changes_name = "#{base_name}_#{build_arch}.changes"
		dsc_name = base_name + '.dsc'
		tar_name = base_name + '.tar.gz'

		files = [deb_name]
		files += [changes_name, dsc_name, tar_name] if @options[:full]

		files.each do |file|
			FileUtils.cp("#{@tmp_dir}/#{file}", Dir.pwd)
		end
	end

	def run!
		begin
			setup!

			copy_files!
			create_patches!

			create_fixed_debian_files!

			create_maintscripts!
			create_install_file!
			create_changelog!
			create_control!

			build_package!
			move_package!
		ensure
			tear_down!
		end
	end

	def pkg_name
		return @debdesc.field('Package').simple_value || @pkg
	end

	def source_pkg
		return pkg_name
	end

	def version
		if @version.nil?
			@version = @debdesc.field('Version').simple_value || '1.0'

			prefix = "~dev" # TODO: make prefix configurable
			date = @now.strftime("%Y%m%d")
			time = @now.strftime("%H%M%S")

			@version += "#{prefix}#{date}.#{time}" if @options[:timestamp]
		end

		return @version
	end

	def maintainer
		return @debdesc.field('Maintainer').simple_value
	end

	def description
		return @debdesc.field('Description').multiline_value # FIXME: check with multiple lines
	end

	def target_arch
		return 'all'
	end

	def build_arch
		return `dpkg-architecture -qDEB_BUILD_ARCH`.strip
	end
end
